[package]
name = "kreuzen-legacy"
version.workspace = true
edition = "2024"

[dependencies]
calmare = { git = "https://github.com/lmaple0/Aureole.git", rev = "9563e4e" }
cp932 = { git = "https://github.com/lmaple0/Aureole.git", rev = "9563e4e" }
kreuzen = { path = "../kreuzen" }
themelios = { git = "https://github.com/lmaple0/Aureole.git", rev = "9563e4e" }
thiserror = "2.0.18"
