[package]
name = "kreuzen"
version.workspace = true
edition = "2024"

[dependencies]
derive_more = { version = "2.1.1", features = ["from", "deref", "deref_mut", "from_str", "debug", "display", "try_from"] }
encoding_rs = "0.8.35"
falcom-sjis = { version = "0.3.0", git = "https://github.com/Aureole-Suite/falcom-sjis.git", rev = "8bf7d1d151081fd1721a4fee7b73274c54b5bc25" }
gospel = { version = "0.4.0", git = "https://github.com/Aureole-Suite/Gospel.git", rev = "9f89bce9d39516d5e7b3c07de510c868af50e134" }
hex = "0.4.3"
regex = { version = "1.12.3", default-features = false, features = ["std", "perf"] }
rootcause = "0.12.1"
tracing = "0.1.44"

[dev-dependencies]
compact-debug = "0.1.4"
pretty_assertions = "1.4.1"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
kreuzen-syntax.path = "../kreuzen-syntax"
rayon = "1.12.0"

[features]
live = []
